### ISSUE TITLE
Refactoring of package names (`cnumr` to `greencodeinitiative`)

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-mobile#20]
**Is your feature request related to a problem? Please describe.**
We migrated our source code from "CNumr" organization (https://github.com/cnumr/ecoCode) to "Green Code Initiative" organization (https://github.com/green-code-initiative/ecoCode-mobile)

**Describe the solution you'd like**
refactor all code source packages from "cnumr" to "greencodeinitiative"

this issue was created once initial issue done on `ecocode` repository : [#40](https://github.com/green-code-initiative/ecoCode/issues/40)

**Comment by dedece35** [comment]
@jhertout, I would like resolve this issue. Do you have some current works in progress or can I do it ?
there will be a lot of modifications :(

**Comment by jhertout** [comment]
For the moment we are only working on ecocode-mobile and I don't think we are concerned by the "cnumr" refactor. So you can go @dedece35

**Comment by dedece35** [comment]
@jhertout, 
you're right : only one reference to `cnumr` in `pom.xml` file on `ios` part.
correction done : https://github.com/green-code-initiative/ecoCode-mobile/commit/2f2ff74a8642c43b9064220a06c44889a9dfac8a
