### ISSUE TITLE
Check and upgrade to Sonar 9.9

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-mobile#22]
The new SonarQube version 9.9 has just been released.
Check installation of plugins and upgrade documentation / docker image if all is ok.

check issue [#56](https://github.com/green-code-initiative/ecoCode/issues/56)

**Comment by dedece35** [comment]
For me, all I could tested is ok with SonarQube 9.9 : build docker, launch docker, check local SonarQube 9.9 (rules are presents).
But I couldn't test it with the test project `ecoCode-mobile-ios-swift-test-project` because launching error.
@jhertout, could you check it, please ?

**Comment by jhertout** [comment]
OK, I will check it @dedece35

**Comment by jhertout** [comment]
It is all good for me.

**Comment by dedece35** [comment]
@olegoaer (and @jhertout) we can now create a new release 1.0.0 for mobile part. are you ok ?

**Comment by jhertout** [comment]
Yes, all is OK. We can create the release.
