### ISSUE TITLE
CodeNarc version 2.2.3 is not found

### ISSUE THREAD

**Issue by qonto-android-team** [green-code-initiative/ecoCode-mobile#31]
**Describe the bug**
When compiling the project, we run into the following error message:
> org.codenarc:CodeNarc:jar:2.2.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced

**To Reproduce**
1. Get the project
2. Compile
3. Error message appears (compilation fails)

**Expected behavior**
The project should compile.

**Screenshots**
<img width="1421" alt="Screenshot 2023-03-17 at 15 41 44" src="https://user-images.githubusercontent.com/87853987/225936921-954f5142-a9aa-46af-a904-647085397a72.png">

**Additional information**
Modifying CodeNarc version to 3.2.0 solves the issue.

**Comment by jhertout** [comment]
Hello, thanks for your issue,

Do not use CodeNarc 3.2.0. CodeNarc 2.2.3 is an internal version build to add our ecoCode Groovy Rules. To build CodeNarc 2.2.3 please follow the steps here:  https://github.com/green-code-initiative/ecoCode-mobile/blob/main/INSTALL.md#preliminary-steps-only-android. Note that this step must be done before building the project with maven. You should clean your local git project (with a git clean -dxf) and rebuild from 0 if you want to use CodeNarc for ecoCode.

- Build CodeNarc (see previous link)
- Build the ecoCode plugin using maven
- Launch the docker

Now, you may use an other version of CodeNarc if you want but you will not have the Android Groovy rules and I cannot guarantee that the project will totally work.

Regards

**Comment by dedece35** [comment]
Hi @qonto-android-team,
is it ok for you (to close this issue) ?

thx

**Comment by qonto-android-team** [comment]
Sure !
