### ISSUE TITLE
[iOS] Sobriety - Disabled Dark Mode (ESOB004)

### ISSUE THREAD

**Issue by Pierre-CGI** [green-code-initiative/ecoCode-mobile#42]
Dark Mode was introduced in iOS 13. It allows the user to switch its system to a dark mode and the apps inherits it automatically by default. Yet is possible to overrides it to light mode by setting the value Light for the key `UIUserInterfaceStyle `in the Information Property List. This should be avoided since displaying dark colors has a significant impact on energy consumption for mobile devices with OLED screens.

**Comment by zippy1978** [comment]
Moved this issue to the new iOs repository here: https://github.com/green-code-initiative/ecoCode-ios/issues/6
