### ISSUE TITLE
[iOS] Power - Save Mode Awareness (EPOW002)

### ISSUE THREAD

**Issue by davidy4ng** [green-code-initiative/ecoCode-mobile#48]
# Description

Use device API to check if low power mode is enabled, and adapt resources usage accordingly. For example, you can reduce frequency of data update if low power mode is enabled. Your app can query the `ProcessInfo.processInfo.isLowPowerModeEnabled` property at any time to determine whether Low Power Mode is active. Your app can also register to receive notifications when the Low Power Mode state of a device changes, using `NSProcessInfoPowerStateDidChange`.

**Comment by zippy1978** [comment]
Addressed by https://github.com/green-code-initiative/ecoCode-mobile/pull/55
