### ISSUE TITLE
[iOS] Sobriety - Animation free (ESOB007)

### ISSUE THREAD

**Issue by jduigoudev** [green-code-initiative/ecoCode-mobile#61]
Related to the Apple iOS documentation : https://developer.apple.com/documentation/swiftui/animations

You can check if you have any animations :
*If you call to the [withAnimation(::)](https://developer.apple.com/documentation/swiftui/withanimation(_:_:)) global function.

If you cal [animation(_:value:)](https://developer.apple.com/documentation/swiftui/view/animation(_:value:)) view modifier to the view.

If you animate changes to a [Binding](https://developer.apple.com/documentation/swiftui/binding) by using the binding’s [animation(_:)](https://developer.apple.com/documentation/swiftui/binding/animation(_:)) method.

**Need to check UIKit and SwiftUI :** 

1. Animations in UIKit:

- [x] UIView.animate(withDuration:animations:)
- [x] UIView.animate(withDuration:animations:completion:)
- [x] UIView.animate(withDuration:delay:options:animations:completion:)
- [x] UIView.animateKeyframes(withDuration:delay:options:animations:completion:)
- [x] UIView.transition(with:duration:options:animations:completion:)
- [x] CABasicAnimation
- [x] CAKeyframeAnimation
- [x] CATransition

2. Animations in SwiftUI:

- [x] withAnimation
- [x] Animation
- [x] AnyTransition
- [ ] .animation(Animation?)
- [ ] .transition(AnyTransition)
- [ ] .onAppear(perform:)
- [ ] .onDisappear(perform:)

**Comment by zippy1978** [comment]
@jduigoudev , I moved this issue to the new iOS repository here : https://github.com/green-code-initiative/ecoCode-ios/issues/7
